version: 0.1.{build}
image:
- Visual Studio 2019
- Visual Studio 2017
- Ubuntu1804
configuration: Release
install:
- cmd: |
    dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: LanguagesSharp.sln
  verbosity: minimal
after_build:
- cmd: >-
    dotnet publish --self-contained false

    dotnet pack

- sh: >-
    dotnet publish --self-contained false

    dotnet pack

artifacts:
- path: '**/*.nupkg'
  name: Nuget
- path: '**/publish/*'
  name: Binaries
test_script:
- cmd: dotnet test --no-build --no-restore --logger:Appveyor
# - sh: dotnet test --no-build --no-restore --logger:Appveyor
# clone_script:
# - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
# - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
